# RGB Underglow - Per-key RGB LEDs
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=75
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=30
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=5
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100

# Per-key RGB Layer Effect
CONFIG_EXPERIMENTAL_RGB_LAYER=y

# HID Indicators (CapsLock indicator in RGB layer)
CONFIG_ZMK_HID_INDICATORS=y


# Enable external power management (RGB power control via P0.27)
CONFIG_ZMK_EXT_POWER=y

# Uncomment the following line to enable OLED Display
# CONFIG_ZMK_DISPLAY=y

# Better wireless performance
CONFIG_BT_CTLR_TX_PWR_PLUS_4=y

# Enable BLE experimental features
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Debounce configuration
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=6

# Low Power States - Go to idle after 2 mins (2*60*1000ms)
CONFIG_ZMK_IDLE_TIMEOUT=120000

# Low Power States - Go to sleep after 30 mins (30*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_SLEEP=y

# Soft Off
CONFIG_ZMK_PM_SOFT_OFF=y

# Battery reporting configuration
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=360

# USB Device Configuration
CONFIG_USB_DEVICE_PID=0xF001
CONFIG_USB_DEVICE_PRODUCT="PH60-SC_V2"
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y